### PR TITLE
added `regex` for regex string assertions

### PR DESCRIPTION
**Pull request by RyanSusana**
Hello, first PR here.

Find a generic regex assertion always handy :)

### CODE REVIEW

**Comment by bschaatsbergen** [comment]
Thank you for your contribution; it’s much appreciated 👏🏼 ! I think adding a regex assertion function for strings in the assert provider is a great idea. Have you considered simplifying the function name to just `regex` instead of `regex_matches`?

**Comment by RyanSusana** [comment]
Done!

**Review by bschaatsbergen — APPROVED** [review]
LGTM 🚀

**Comment by bschaatsbergen** [comment]
Thank you for your contribution @RyanSusana! 👏🏼

**Pull request merged**
